apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-validator-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-validator-service
  template:
    metadata:
      labels:
        app: config-validator-service
    spec:
      containers:
        - name: config-validator-service
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
